name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          architecture: x64
          cache: maven
      - name: Run tests of modules
        run: mvn test --batch-mode --update-snapshots --projects sage-jena-tdb2,sage-jena-volcano -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

